### ISSUE TITLE
pretraining without annotation

### ISSUE THREAD

**Issue by awesome-crab** [nadavbra/protein_bert#10]
Hello and thank you for this amazing github repository protein_bert!

Im thinking about pretraining the protein_bert model from scratch on very short sequences (7 to 20 acids, cdrs from tcr for example).
I have a large fasta-file containing millions of those very short sequences. But because these sequences are very variable and there is a vast amount of sequences, I have no annotation to the sequences.

When I try to run following command to create the h5 file which is used for pretraining:
` nohup create_uniref_h5_dataset --protein-fasta-file=fasta_file.fasta --output-h5-dataset-file=./dataset.h5 --min-records-to-keep-annotation=100 >&! ./log_create_uniref_h5_dataset.txt`
I get the error message:
`create_uniref_h5_dataset: error: the following arguments are required: --protein-annotations-sqlite-db-file, --go-annota
tions-meta-csv-file`

Should I provide an empty db-file and an empty csv-file for create_uniref_h5_dataset or should I directly create a h5-file from the fasta which will be used as input for pretrain_proteinbert? What would I have to consider when creating an h5-file with the sequences?
Or could you think of a way how I could pretrain protein-bert on the described fasta file without annotation?
Is it even possible to pretrain protein_bert on only sequences without annotation?

Any help is highly appreciated!

**Comment by nadavbra** [comment]
Hi @awesome-crab,

In principle you should be able to train ProteinBERT without GO annotations. You can either feed it with all-zero vectors or any other global features that seem appropriate for your specific use-case. However, the current scripts assume that you create an h5 dataset from UniRef (with GO annotations).

If you are comfortable with writing a little bit of Python code, I think the best solution for you would be to skip the pretraining script and pretrain ProteinBERT using the Python API (using the functions in the [pretraining](https://github.com/nadavbra/protein_bert/blob/master/proteinbert/pretraining.py) submodule). Specifically I imagine you'd want to override `DatasetHandler` to load sequences from your file instead of an h5 dataset.

BTW, it's funny that you are interested in training a protein language model for TCR sequences. I've considered working on a very similar project myself. If you think you might be open for collaboration, feel free to send me an email :)
(Of course, if you want to continue working on this project on your own, that's perfectly understandable.)

Best,
Nadav Brandes
