### ISSUE TITLE
Viral Yield Prediction with ProteinBERT

### ISSUE THREAD

**Issue by williamtbarker** [nadavbra/protein_bert#58]
Hi all, thanks in advance- I am a virologist with limited coding experience. I have protein sequences of several viral strains along with their associated yield in a csv file. I want to build an ML model with proteinBERT that takes a given sequence as an input and gives a predicted yield as an output. Is this possible with your model? And if so where do I begin?

**Comment by nadavbra** [comment]
@williamtbarker Yes should definitely be possible.
Take a look at our [demo notebook](https://github.com/nadavbra/protein_bert/blob/master/ProteinBERT%20demo.ipynb).

**Comment by williamtbarker** [comment]
I've looked over the demo notebook and have the code working on my machine at home, but I'm still fairly lost on the next steps. Could you provide guidance on how to setup the Output of the model for a regression task? Or will this require building a new model on my end?

**Comment by r-kellerm** [comment]
@williamtbarker - for changing the learning task to regression you have to change the output type to numeric and set the labels to None. e.g. instead of:
```
# A local (non-global) binary output
OUTPUT_TYPE = OutputType(False, 'binary')
UNIQUE_LABELS = [0, 1]
OUTPUT_SPEC = OutputSpec(OUTPUT_TYPE, UNIQUE_LABELS)
```
Use:
# A local (non-global) numeric output
```
OUTPUT_TYPE = OutputType(False, 'numeric')
UNIQUE_LABELS = None
OUTPUT_SPEC = OutputSpec(OUTPUT_TYPE, UNIQUE_LABELS)
```
The loss function (MSE) and the evaluation metric (Spearman correlation) are selected automatically based on the `OutputType `argument.
